### ISSUE TITLE
About transforms.Normalize

### ISSUE THREAD

**Issue by lanson07** [yyk-wew/F3Net#10]
Hi!
I found that, in your code(util.py), you didn't use transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) to normalize the raw data. Did this paper really not need this operation, or was this code forgotten?
Thank you for your reply！

**Comment by yyk-wew** [comment]
Hi.
Actually I do min-max normalization instead of zero-mean normalization, this operation is implemented in **get_item** function.
https://github.com/yyk-wew/F3Net/blob/574667f94569287a21bf5ceb4fed63f61848d528/utils.py#L55

And, in the experiment, I found that normalization is very important for F3-Net because it uses pre-trained parameters which is trained on normalized images. But I'm not sure which is better, min-max or z-score. Have a try if interested.

**Comment by lanson07** [comment]
Thanks for your reply!
I will try both, thank you!

**Comment by linfeng-789** [comment]
> Thanks for your reply! I will try both, thank you!

想请教一下您两个实验的比较结论
